name: chocolatine
run-name: chocolatine
on: [push, pull_request]

env:
    - MIRROR_URL: ""
    - EXECUTABLES: ""

jobs:
    check_coding_style:
        runs-on: ghcr.io/epitech/coding-style-checker:latest
        steps:
        - uses: actions/checkout@v3
        - run: check.sh $(pwd) $(pwd)

    check_program_compilation:
        needs: [check_coding_style]
        runs-on: epitechcontent/epitest-docker:latest
        steps:
        - uses: actions/checkout@v3
        - run: make
        - run: make clean
        - if: [ ! -f ${{ EXEXCUTABLES }} ]
          run: exit(1)

    run_test:
        needs: [check_program_compilation]
        runs_on: epitechcontent/epitest-docker:latest
        steps:
        - uses: actions/checkout@v3
        - run: make tests_run

    push_to_mirror:
        if: ${{ github.event_name == "push" }}
        needs: [run_test]
        runs_on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: pixta-dev/repository-mirroring-action@v1
          with:
            target_repo_url:
                MIRROR_URL
            ssh_private_key:
                ${{ secrets.GIT_SSH_PRIVATE_KEY }}

