name: chocolatine
run-name: chocolatine

on: [push, pull_request]

env:
    MIRROR_URL: "git@github.com:EpitechPromo2027/B-DOP-200-LYN-2-1-chocolatine-lee.bingler.git"
    EXECUTABLES: "antman,giantman"

jobs:
    check_coding_style:
        runs-on: ubuntu-latest
        container: ghcr.io/epitech/coding-style-checker:latest
        steps:

        - name: checkout
          uses: actions/checkout@v3

        - name: run_coding_style
          run: check.sh $(pwd) $(pwd)
          continue-on-error: true

        - name: check_is_theres_an_coding_style_error
          run: |
            if [ ! -f "coding-style-reports.log" ]; then
              exit 0
            elif [ $(wc -c "coding-style-reports.log" | awk '{print $1}') === "0" ]; then
              exit 0
            fi
            exit 1

        - name: display_error
          if: ${{ failure() }}
          run: |
            input='coding-style-reports.log'
            IFS=':'
            i=0
            while read -r line; do
              if [ $i == 0 ]; then
                  firstLine="$line"
                  printf "first $firstLine\n\n"
              fi  

              read -a strarr <<< "$line"

              if [[ $i != 0 ]] && [[ $firstLine == $line ]]; then
                  break
              fi

              strarr[0]=$(echo "${strarr[0]}" | sed -r 's/^.{2}//')
              strarr[2]=$(echo "${strarr[2]}" | sed -r 's/^.{1}//')
              echo "::error file=${strarr[0]},line=${strarr[1]},endLine=$((${strarr[1]} + 1)),col=0,title="${strarr[2]} coding style error"::${strarr[3]}"
              i=$((i+1))
            done < "$input"

    check_program_compilation:
        needs: [check_coding_style]
        runs-on: ubuntu-latest
        container: epitechcontent/epitest-docker:latest

        steps:
        - name: checkout
          uses: actions/checkout@v3

        - name: make_the_binarie
          run: make
          timeout-minutes: 2
        
        - name: make_clean
          run: make clean
          timeout-minutes: 2

        - name: check_exec_list_exist
          run: |
              IFS=',' read -r -a array << $EXECUTABLES
              for i in "${array[@]}"
              do
                  if [ ! -x $"i" ]; then
                      echo "::error::Binarie $i does not exist.\n"
                      exit 1
                  fi
              done

    run_test:
        needs: [check_program_compilation]
        runs-on: ubuntu-latest
        container: epitechcontent/epitest-docker:latest

        steps:
        - name: checkout
          uses: actions/checkout@v3

        - name: test_run
          run: make tests_run

    push_to_mirror:
        if: ${{ github.event_name == 'push' }}
        needs: [run_test]
        runs-on: ubuntu-latest

        steps:
        - name: checkout
          uses: actions/checkout@v3
          with: 
            fetch-depth: 0

        - name: mirroring
          uses: pixta-dev/repository-mirroring-action@v1
          with:
            target_repo_url:
              ${{ env.MIRROR_URL }}
            ssh_private_key:
                ${{ secrets.GIT_SSH_PRIVATE_KEY }}
